version: "3.8"
services:
    
  gateway:
    build: ./nginx
    container_name: gateway
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - app
  
  app:
    build: .
    depends_on:
      pgdb:
        condition: service_healthy
    environment:
      PORT: 8000
      DB_HOST: pgdb
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: 1234
      DB_NAME: django101
      PRODUCTION_HOST: app
      GATEWAY_HOST: gateway
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@gmail.com
      DJANGO_SUPERUSER_PASSWORD: 1234
    deploy:
      replicas: 3
    networks:
      - mynetwork
    entrypoint: ["/app/wait-for-it.sh", "pgdb:5432", "--", "sh", "-c", "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"]

networks:
  mynetwork:
    driver: bridge
